export const LOGIN_URL = '/auth/login';
export const REGISTER_URL = '/auth/register';
export const LOGOUT_URL = '/auth/logout';
export const PROFILE_URL = '/users/profile';
export const CHAT_URL = '/ai/generate/stream';
export const FETCH_CHATS_URL = '/ai/chats';
export const FETCH_CONVERSATION_URL = '/ai/chats/:chatId';
export const ENHANCE_PROMPT_URL = '/ai/enhance-prompt';
export const UPDATE_CONVERSATION_TITLE_URL = (chatId: string) => `/ai/chats/${chatId}/title`;
export const DELETE_CONVERSATION_URL = (chatId: string) => `/ai/chats/${chatId}`;